# Utilise une image de base officielle de Python
FROM python:3.8-slim

# Définit le répertoire de travail dans le conteneur
WORKDIR /app

# Copie le fichier requirements.txt dans le répertoire de travail
COPY requirements.txt .

# Installe les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copie le reste des fichiers de l'application dans le répertoire de travail
COPY . .

# Définit la commande par défaut à exécuter lorsque le conteneur démarre

CMD ["python", "app.py"]
